sudo: required

language: node_js
node_js: "14"

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -f Dockerfile -t quay.io/microcks/microcks-hub:latest .;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-hub:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    docker build -f Dockerfile -t quay.io/microcks/microcks-hub:$TRAVIS_TAG .;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-hub:$TRAVIS_TAG;
    fi
